name: Additionally API Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AWS Amplify
      run: |
          echo "Deploying to AWS Amplify"
          URL="${{ secrets.WEBHOOK_URL }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
    - name: Status of Deployment
      run: echo "Completed"
